### ISSUE TITLE
Move form validation to form request objects.

### ISSUE THREAD

**Issue by michaelbunch** [bmaxwell112/user-bookmarking-platform#2]
In Laravel you can create custom request objects that contain form field validation. This is useful for keep controllers lean and maintaining validation rules in a central location.

https://laravel.com/docs/5.6/validation#form-request-validation

https://github.com/bmaxwell112/user-bookmarking-platform/blob/415b3f0b0df3a7efd2c05a013751aa1b92785b0b/app/Http/Controllers/BookmarksController.php#L30-L33

**Comment by bmaxwell112** [comment]
Updated validation to use custom request object.
