### ISSUE TITLE
Use route model bindings

### ISSUE THREAD

**Issue by michaelbunch** [bmaxwell112/user-bookmarking-platform#3]
In Laravel you can bind a route parameter to a model that will be injected into the controller. The injected model has already performed a `Model::findOrFail()` and is ready for immediate use.

https://laravel.com/docs/5.6/routing#route-model-binding

https://github.com/bmaxwell112/user-bookmarking-platform/blob/master/app/Http/Controllers/BookmarksController.php#L53

**Comment by bmaxwell112** [comment]
Updated to use route-model-binding.
