### ISSUE TITLE
Missing trailing `;` on lines 14 and 16

### ISSUE THREAD

**Issue by michaelbunch** [bmaxwell112/user-bookmarking-platform#4]
https://github.com/bmaxwell112/user-bookmarking-platform/blob/26f388d194c922adcba0fe19119b8b27ccfb4340/routes/web.php#L14

**Comment by bmaxwell112** [comment]
Interesting that it not throw any errors. I was able to login create and remove posts before I pushed the last changes. I've updated the code for those lines.
